// Generated by CoffeeScript 1.7.1
var LOCAL_STORAGE_PREFIX, buildKey, localStorage, memoryCache;

LOCAL_STORAGE_PREFIX = 'cachedResource://';

localStorage = window.localStorage;

memoryCache = {};

buildKey = function(key) {
  return "" + LOCAL_STORAGE_PREFIX + key;
};

module.exports = {
  getItem: function(key, fallbackValue) {
    var item;
    key = buildKey(key);
    item = memoryCache[key];
    if (item == null) {
      item = localStorage.getItem(key);
    }
    if (item != null) {
      return angular.fromJson(item);
    } else {
      return fallbackValue;
    }
  },
  setItem: function(key, value) {
    var stringValue;
    key = buildKey(key);
    stringValue = angular.toJson(value);
    try {
      localStorage.setItem(key, stringValue);
      if (memoryCache[key] != null) {
        delete memoryCache[key];
      }
    } catch (_error) {
      memoryCache[key] = stringValue;
    }
    return value;
  },
  clearAll: function() {
    var i, key, keys, _i, _len, _results;
    keys = (function() {
      var _i, _ref, _results;
      _results = [];
      for (i = _i = 0, _ref = localStorage.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        _results.push(localStorage.key(i));
      }
      return _results;
    })();
    _results = [];
    for (_i = 0, _len = keys.length; _i < _len; _i++) {
      key = keys[_i];
      if (key.indexOf(LOCAL_STORAGE_PREFIX) === 0) {
        _results.push(localStorage.removeItem(key));
      }
    }
    return _results;
  }
};
