// Generated by CoffeeScript 1.7.1
var LOCAL_STORAGE_PREFIX;

LOCAL_STORAGE_PREFIX = 'cachedResource://';

module.exports = window.localStorage != null ? {
  getItem: function(key, fallback) {
    var item;
    item = localStorage.getItem("" + LOCAL_STORAGE_PREFIX + key);
    if (item != null) {
      return angular.fromJson(item);
    } else {
      return fallback;
    }
  },
  setItem: function(key, value) {
    localStorage.setItem("" + LOCAL_STORAGE_PREFIX + key, angular.toJson(value));
    return value;
  }
} : {
  getItem: function(key, fallback) {
    return fallback;
  },
  setItem: function(key, value) {
    return value;
  }
};
