// Generated by CoffeeScript 1.7.1
var modifyObjectInPlace;

module.exports = modifyObjectInPlace = function(oldObject, newObject) {
  var key, _i, _j, _len, _len1, _ref, _ref1, _results;
  _ref = Object.keys(oldObject);
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    key = _ref[_i];
    if (key[0] !== '$') {
      if (newObject[key] == null) {
        delete oldObject[key];
      }
    }
  }
  _ref1 = Object.keys(newObject);
  _results = [];
  for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
    key = _ref1[_j];
    if (key[0] !== '$') {
      if (angular.isObject(oldObject[key]) && angular.isObject(newObject[key])) {
        _results.push(modifyObjectInPlace(oldObject[key], newObject[key]));
      } else if (!angular.equals(oldObject[key], newObject[key])) {
        _results.push(oldObject[key] = newObject[key]);
      } else {
        _results.push(void 0);
      }
    }
  }
  return _results;
};
