// Generated by CoffeeScript 1.7.1
var ResourceCacheArrayEntry, ResourceCacheEntry,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ResourceCacheEntry = require('./resource_cache_entry');

ResourceCacheArrayEntry = (function(_super) {
  __extends(ResourceCacheArrayEntry, _super);

  function ResourceCacheArrayEntry() {
    return ResourceCacheArrayEntry.__super__.constructor.apply(this, arguments);
  }

  ResourceCacheArrayEntry.prototype.defaultValue = [];

  ResourceCacheArrayEntry.prototype.setKey = function(key) {
    return this.key = "" + key + "/array";
  };

  return ResourceCacheArrayEntry;

})(ResourceCacheEntry);

module.exports = ResourceCacheArrayEntry;
